### PR TITLE
Queries optimization and bootstrap templates with barcharts

### PR DESCRIPTION
**Pull request by synw**
- Queries optimization using prefetch_related and related_name
- Bootstrap templates with barcharts using widthratio templatetag
- Views optimization 
- Added a control in the PollVoteView post method to check if a user can really post

### CODE REVIEW

**Comment by noxan** [comment]
I appreciate your efforts on extending the validation and the functionality while updating this app in general a lot! But on the other side I have several comments regarding the changes you introduce:

1) I cannot understand the necessity to flag all those fields as nullable, what is the reason for this change? For the user field I get the point of keeping votes of deleted users instead of deleting them as well, which I like in general except for the nullable, which prevents any kind of tracking and could encourage users to fake votes by registering and deleting their user afterwards.

2) The south migrations are outdated and should be replaced with django core migrations, true. But just deleted the old ones is not the proper solution in my opinion. There are still some django projects out there using south and we should keep this app compatible for a while. There are further details in the south docs or here in the django docs: https://docs.djangoproject.com/en/1.8/topics/migrations/#libraries-third-party-apps

3) Is there any reason you are using the django user model hard-coded? Otherwise I would recommend the django docs regarding this topic: https://docs.djangoproject.com/en/1.8/topics/auth/customizing/#referencing-the-user-model

4) Adding some basic bootstrap styling was once my goal as well as you might have guessed from the few button classes, but nowadays I think there exist so many different frameworks, that we should stick very basic templates without any specific styling, since it does only help a few and in the end (almost) everybody will have some custom styling and will replace the provided templates. I am open to a discussion on this point, maybe providing yours as optional ones, but containing a complete layout is too much in my opinion. 

Excuse my extensive feedback and thanks once more for your contribution @synw :)

**Comment by synw** [comment]
Thanks for your feedback. 

1) I usually flag the fields null=True to avoid problems during migrations. I removed all this.

2) Sorry about that, I'm on Django 1.8 but I understand the backward compatibility concerns.

3) You are right: I was not aware of this, sorry. Corrected.

4) Well the point here is that people like to have apps ready to use. It can save time for the people. As you suggested maybe we can make it an option using a `POLLS_TEMPLATE_SET="basic"` and use it with the template_name property in the views? This way we could have other template sets for other frameworks.

5) Added a french translation

**Comment by synw** [comment]
Made a proposition for a POLLS_TEMPLATE_SET setting. If not set the default templates you provided will be used.

**Comment by synw** [comment]
Sorry for all these little commits, I had to make minor corrections.

**Comment by noxan** [comment]
Sorry for the delayed feedback, I keep being busy. But your changes look a lot better now to me :+1: 

1, 2, 3 done, 5 sweet! I would like to merge those changes independent of the templates if possible. For this concern I would like to have common solution for all the apps we maintain here and this might take some discussion...
Finally I need a calm moment to go into the details of the voting check you implemented. Apart from that I just realized that the test cases somehow fail, I will try to have a look myself as soon as I find the time - guess the test setup for this app is quite outdated meanwhile...

Little commits are just perfect, then you have better tracking of what's going on plus merging or even reverting changes is easier ;)

**Comment by synw** [comment]
For the build fail it is because of the south migrations you kept: `django.db.migrations.loader.BadMigrationError: Migrated app 'polls' contains South migrations. Make sure all numbered South migrations are deleted prior to creating Django migrations.`
Maybe you can make a branch with that old stuff?

One more thing: I need to control the order of the choices, so I will implement this functionality. By the way I may provide random barchart colors with bootstrap classes for eye candy in the bootstrap templates set.

**Comment by synw** [comment]
- Added an order field for the choices to control the display order. 
- Added a translatable app label
- Removed the old south migrations to avoid the build to fail

**Comment by synw** [comment]
Build is now passing

**Pull request closed without merging**
